//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscuelaDBEntities : DbContext
    {
        public EscuelaDBEntities()
            : base("name=EscuelaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catedra> Catedras { get; set; }
        public virtual DbSet<Cursada> Cursadas { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<UsuarioLogin> Logins { get; set; }
        public virtual DbSet<Maestro> Maestros { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<CursadaAlumno> Cursadas_Alumno { get; set; }
        public virtual DbSet<ListadoCatedra> Listado_Catedras { get; set; }
    }
}
