//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoCatedra
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Dia { get; set; }
        public string Horario { get; set; }
        public string Turno { get; set; }
        public string Maestro { get; set; }
    }
}
